[project]
name = "agntcy-app-sdk"
version = "0.5.5"
description = "Agntcy Application SDK for Python"
authors = [{ name = "Cody Hartsook", email = "codyhartsook@gmail.com" }]
requires-python = ">=3.12,<4.0"
license = "Apache-2.0"
readme = "README.md"
dependencies = [
    "a2a-sdk==1.1.0",
    "nats-py==2.12.0",
    "structlog==25.5.0",
    "langchain-community==0.4.1",
    "uvicorn==0.38.0",
    "mcp[cli]==1.20.0",
    "httpx==0.28.1",
    "ioa-observe-sdk==1.0.49",
    "asgi-lifespan==2.1.0",
    "slim-bindings==2.2.0",
    "agntcy-identity-service-sdk==0.0.7",
    "slima2a==0.7.0",
    "agntcy-dir==1.0.0",
]

[project.urls]
"Homepage" = "https://github.com/agntcy/app-sdk"
"Bug Tracker" = "https://github.com/agntcy/app-sdk/issues"

[dependency-groups]
dev = [
    "pytest==7.4.4",
    "pytest-asyncio==0.17.2",
    "pytest-cov==4.1.0",
    "typing-extensions==4.15.0",
    "tiktoken==0.8.0",
    "openai==1.109.1",
    "langchain-anthropic==0.3.21",
    "langchain-openai==0.3.34",
    "mypy==1.19.1",
    "types-protobuf==6.32.1.20260221",
    "ruff==0.15.2",
]

[tool.pytest.ini_options]
asyncio_mode = "strict"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
