# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Setup Python Environment
description: setup environment to build/test/lint python applications
inputs:
  py-install:
    description: "Install Python"
    required: false
    default: "false"
  py-version:
    description: "Python version to install"
    required: false
    default: "3.12"
  uv-install:
    description: "Install uv"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      if: ${{ inputs.py-install == 'true' }}
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.py-version }}

    - name: Setup Taskfile
      uses: ./.github/actions/setup-task
      with:
        version: latest
        cache-enabled: true

    - name: Install uv (unix)
      if: ${{ inputs.uv-install == 'true' && runner.os != 'Windows' }}
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="${HOME}/.local/bin" sh

    - name: Install uv (windows)
      if: ${{ inputs.uv-install == 'true' && runner.os == 'Windows' }}
      shell: bash
      run: |
        powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

    - name: Update GITHUB_PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
